package org.codealpha.gmsservice.constants;

public enum AppConfiguration {

  KPI_REMINDER_NOTIFICATION_DAYS("KPI_REMINDER_NOTIFICATION_DAYS"),
  KPI_SUBMISSION_WINDOW_DAYS("KPI_SUBMISSION_WINDOW_DAYS"),
  SUBMISSION_ALTER_MAIL_SUBJECT("SUBMISSION_ALTER_MAIL_SUBJECT"),
  SUBMISSION_ALTER_MAIL_CONTENT("SUBMISSION_ALTER_MAIL_CONTENT"),
  GRANT_ALERT_NOTIFICATION_MESSAGE("GRANT_ALERT_NOTIFICATION_MESSAGE"),
  GRANT_STATE_CHANGED_MAIL_MESSAGE("GRANT_STATE_CHANGED_MAIL_MESSAGE"),
  GRANT_STATE_CHANGED_MAIL_SUBJECT("GRANT_STATE_CHANGED_MAIL_SUBJECT"),
  REPORT_STATE_CHANGED_MAIL_MESSAGE("REPORT_STATE_CHANGED_MAIL_MESSAGE"),
  REPORT_STATE_CHANGED_MAIL_SUBJECT("REPORT_STATE_CHANGED_MAIL_SUBJECT"),
  PLATFORM_EMAIL_FOOTER("PLATFORM_EMAIL_FOOTER"),
  REPORT_DUE_DATE_INTERVAL("REPORT_DUE_DATE_INTERVAL"),
  REPORT_SETUP_INTERVAL("REPORT_SETUP_INTERVAL"),
  REPORT_PERIOD_INTERVAL("REPORT_PERIOD_INTERVAL");

  private String val;

  AppConfiguration(String value) {
    this.val = value;
  }
}
