package org.codealpha.gmsservice.constants;

public enum AppConfiguration {

  KPI_REMINDER_NOTIFICATION_DAYS("KPI_REMINDER_NOTIFICATION_DAYS"),
  KPI_SUBMISSION_WINDOW_DAYS("KPI_SUBMISSION_WINDOW_DAYS"),
  SUBMISSION_ALTER_MAIL_SUBJECT("SUBMISSION_ALTER_MAIL_SUBJECT"),
  SUBMISSION_ALTER_MAIL_CONTENT("SUBMISSION_ALTER_MAIL_CONTENT"),
  GRANT_ALERT_NOTIFICATION_MESSAGE("GRANT_ALERT_NOTIFICATION_MESSAGE"),
  GRANT_STATE_CHANGED_MAIL_MESSAGE("GRANT_STATE_CHANGED_MAIL_MESSAGE"),
  GRANT_STATE_CHANGED_MAIL_SUBJECT("GRANT_STATE_CHANGED_MAIL_SUBJECT"),
  GRANT_STATE_CHANGED_NOTIFICATION_MESSAGE("GRANT_STATE_CHANGED_NOTIFICATION_MESSAGE"),
  GRANT_STATE_CHANGED_NOTIFICATION_SUBJECT("GRANT_STATE_CHANGED_NOTIFICATION_SUBJECT"),
  REPORT_STATE_CHANGED_MAIL_MESSAGE("REPORT_STATE_CHANGED_MAIL_MESSAGE"),
  REPORT_STATE_CHANGED_MAIL_SUBJECT("REPORT_STATE_CHANGED_MAIL_SUBJECT"),
  REPORT_STATE_CHANGED_NOTIFICATION_MESSAGE("REPORT_STATE_CHANGED_NOTIFICATION_MESSAGE"),
  REPORT_STATE_CHANGED_NOTIFICATION_SUBJECT("REPORT_STATE_CHANGED_MAIL_SUBJECT"),
  PLATFORM_EMAIL_FOOTER("PLATFORM_EMAIL_FOOTER"), REPORT_DUE_DATE_INTERVAL("REPORT_DUE_DATE_INTERVAL"),
  REPORT_SETUP_INTERVAL("REPORT_SETUP_INTERVAL"), REPORT_PERIOD_INTERVAL("REPORT_PERIOD_INTERVAL"),
  GRANT_INVITE_SUBJECT("GRANT_INVITE_SUBJECT"), GRANT_INVITE_MESSAGE("GRANT_INVITE_MESSAGE"),
  REPORT_INVITE_SUBJECT("REPORT_INVITE_SUBJECT"), REPORT_INVITE_MESSAGE("REPORT_INVITE_MESSAGE"),
  INVITE_SUBJECT("INVITE_SUBJECT"), INVITE_MESSAGE("INVITE_MESSAGE"),
  DUE_REPORTS_REMINDER_SETTINGS("DUE_REPORTS_REMINDER_SETTINGS"),
  ACTION_DUE_REPORTS_REMINDER_SETTINGS("ACTION_DUE_REPORTS_REMINDER_SETTINGS"),
  GENERATE_GRANT_REFERENCE("GENERATE_GRANT_REFERENCE"), FORGOT_PASSWORD_MAIL_SUBJECT("FORGOT_PASSWORD_MAIL_SUBJECT"),
  FORGOT_PASSWORD_MAIL_MESSAGE("FORGOT_PASSWORD_MAIL_MESSAGE"),
  DISBURSEMENT_STATE_CHANGED_MAIL_SUBJECT("DISBURSEMENT_STATE_CHANGED_MAIL_SUBJECT"),
  DISBURSEMENT_STATE_CHANGED_MAIL_MESSAGE("DISBURSEMENT_STATE_CHANGED_MAIL_MESSAGE"),
  DISBURSEMENT_STATE_CHANGED_NOTIFICATION_MESSAGE("DISBURSEMENT_STATE_CHANGED_NOTIFICATION_MESSAGE"),
  DISBURSEMENT_STATE_CHANGED_NOTIFICATION_SUBJECT("DISBURSEMENT_STATE_CHANGED_NOTIFICATION_SUBJECT"),
  OWNERSHIP_CHANGED_EMAIL_MESSAGE("OWNERSHIP_CHANGED_EMAIL_MESSAGE"),
  OWNERSHIP_CHANGED_EMAIL_SUBJECT("OWNERSHIP_CHANGED_EMAIL_SUBJECT"),
  OWNERSHIP_CHANGED_NOTIFICATION_MESSAGE("OWNERSHIP_CHANGED_NOTIFICATION_MESSAGE"),
  OWNERSHIP_CHANGED_NOTIFICATION_SUBJECT("OWNERSHIP_CHANGED_NOTIFICATION_SUBJECT");

  private String val;

  AppConfiguration(String value) {
    this.val = value;
  }
}
