spring:
  profiles:
    active: qa
---

spring:
  profiles: qa
  datasource:
    url: jdbc:postgresql://localhost:5432/gms
    username: apple
    password:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
---