spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform:
  upload-file-location:
  supported-file-types:
  servlet:
    multipart:
      max-file-size:

  send-mail: true
logging:
  level:
    org.codealpha: info
  file:

---
spring:
  profiles: local
  send-mail: false
  datasource:
    url:
    username:
    password:
    initialization-mode: always
    platform:
  jpa:
    database:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation:
      ddl-auto: none
  jackson:
    default-property-inclusion:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api