spring:
  profiles:
    active: qa
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  upload-file-location: /opt/gms/storage/
  send-mail: true
logging:
  level:
    org.codealpha: info
  file: gms.log
---

spring:
  profiles: dev
  upload-file-location: /Users/apple/storage/
  send-mail: false
  datasource:
    url: jdbc:postgresql://localhost:5432/anudan
    username: apple
    password:
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ranjit.victor@enstratify.com
    password: enstratify123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
spring:
  profiles: uat
  datasource:
    url: jdbc:postgresql://localhost:5432/anudan
    username: postgres
    password: anudan123$
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ranjit.victor@enstratify.com
    password: enstratify123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
spring:
  profiles: qa
  datasource:
    url: jdbc:postgresql://localhost:5432/gms
    username: postgres
    password: SA#1029
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ranjit.victor@enstratify.com
    password: enstratify123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
