spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  upload-file-location: /opt/gms/storage/
  send-mail: true
logging:
  level:
    org.codealpha: info
  file: gms.log

---
spring:
  profiles: local
  send-mail: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
    platform: pg
  jpa:
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.office365.com
    port: 587
    username: admin@anudan.org
    password: admin@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
spring:
  profiles: qa
  datasource:
    url: jdbc:postgresql://localhost:5432/anudan
    username: postgres
    password: anudan123$
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.office365.com
    port: 587
    username: admin@anudan.org
    password: admin@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gms
    username: postgres
    password: SA#1029
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.office365.com
    port: 587
    username: admin@anudan.org
    password: admin@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
spring:
  profiles: uat
  datasource:
    url: jdbc:postgresql://db-postgresql-uat-anudan-do-user-2489687-0.db.ondigitalocean.com:25060/anudan
    username: doadmin
    password: b1kco73705ispui1
    initialization-mode: always
    platform: pg
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.office365.com
    port: 587
    username: admin@anudan.org
    password: admin@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api