spring:
  profiles:
    active: qa
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    org.codealpha: info
  file: gms.log
---

spring:
  profiles: qa
  datasource:
    url: jdbc:postgresql://localhost:5432/gms
    username: postgres
    password:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ranjit.victor@enstratify.com
    password: enstratify123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
---
