update workflow_statuses set name='Record Disbursement',display_name='Record Disbursement' where id = 33;
update workflow_statuses set name='Record Disbursement',display_name='Record Disbursement' where id = 92;
update workflow_status_transitions set action='Publish to Partner' where id=57;
update workflow_status_transitions set action='Submit to Finance' where id=59;
update workflow_status_transitions set action='Submit to Hub' where id=60;
update workflow_status_transitions set action='Approve Report' where id=61;
update workflow_status_transitions set action='Submit Internally' where id=125;
update workflow_status_transitions set action='Submit to Finance' where id=130;
update workflow_status_transitions set action='Submit to Hub' where id=126;
update workflow_status_transitions set action='Approve Report' where id=127;
update workflow_status_transitions set action='Submit to Hub' where id=69;
update workflow_status_transitions set action='Submit to Finance' where id=70;
update workflow_status_transitions set action='Submit to CEO/ED' where id=71;
update workflow_status_transitions set action='Approve Request' where id=75;
update workflow_status_transitions set action='Submit Disbursement' where id=76;
update workflow_status_transitions set action='Submit to Hub' where id=140;
update workflow_status_transitions set action='Submit to Finance' where id=141;
update workflow_status_transitions set action='Submit to CEO/ED' where id=142;
update workflow_status_transitions set action='Approve Request' where id=143;
update workflow_status_transitions set action='Submit Disbursement' where id=144;